SUCCESS = "SUCCESS"
SUCCESS_NO_RESULTS = "SUCCESS_NO_RESULTS"
FETCH_ERROR = "FETCH_ERROR"
PARSE_ERROR = "PARSE_ERROR"
SCHEMA_CHANGED = "SCHEMA_CHANGED"

ALERT_TYPES = {
    "VULNERABILITY",
    "SECURITY_ADVISORY",
    "SECURITY_GUIDANCE",
    "AUTH_CHANGE",
    "BREAKING_CHANGE",
    "DEPRECATION",
}

ACTIVE_RELEVANCE = {"RELEVANT", "REVIEW", "INFORMATIONAL"}
